# Generated by Django 6.1.1 on 2026-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wormbase_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('sequence_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('gene_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('other_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('gene_type', models.CharField(db_index=True, max_length=64)),
            ],
        ),
    ]
